### ISSUE TITLE
Support for Timeline column type

### ISSUE THREAD

**Issue by jonpxpx** [allejo/PhpPulse#11]
Hey, are you planning on implementing the new Column Types like Timeline?

We are writing an app for our agency to pull pulses from all boards and would be good to make use of these (mainly Numbers). Timeline we are planning on implementing in our own way using a start and end date.

Do you accept PR's if we get time to implement this?

Many thanks,
Jon

**Comment by allejo** [comment]
All of the current column types available through the [API](https://developers.dapulse.com/#!/boards) are supported; number columns are available as ["numeric columns"](https://github.com/allejo/PhpPulse/blob/99d198849597cd537ebabf00d427cf941118e10c/src/Pulse.php#L367-L388) and ["numeric values"](https://github.com/allejo/PhpPulse/blob/99d198849597cd537ebabf00d427cf941118e10c/src/Objects/PulseColumnNumericValue.php).

As for supporting a "timeline" column, would you mind elaborating on that? I had been thinking of having a `PulseUtilities` class (or namespace) with convenience functions for such things. For now, I'm thinking about keeping it separate from objects (i.e. Pulse, PulseBoard) as I'd want those classes to mirror the API as closely as possible.

But yes, I gladly welcome pull requests if you have any new features, improvements, or fixes! 👍

**Comment by jonpxpx** [comment]
Great, thanks for coming back to me.

At the moment, I am not too worried about the Timeline as we are building our own internally since the User API was released as we need something a little different to the direction Dapulse is taking as well as an integration with Toggl.

A couple things I am looking at currently are: 

- [ ] Implementing the endpoint for grabbing a single update (for those updates where they are tagged on a status column) - We currently grab all updates for the pulse and match against the json > value > update_id
- [ ]  Implement a way to match against labels instead of values on status columns - we are looping labels and then grabbing the matched id (strange naming convention they have going on).
- [ ] Figure out how we can force our data to be updated - Dapulse seems to cache for a certain period.

I will probably fork this in the new year and put a PR together for anything usable that we come up with as well as get my guys involved too.

Thanks for coming back to me and sorry for the delay - Last day in the office today.

**Comment by allejo** [comment]
Sounds good! I look forward to seeing what you guys come up with 👍

**Comment by allejo** [comment]
Closing this since the initial request for the timeline column has been completed. Feel free to open up a new issue/pr with any further discussion.
