### ISSUE TITLE
Update pulse column values

### ISSUE THREAD

**Issue by mattpfeffer** [allejo/PhpPulse#13]
Am I being daft or is there a way to update the column values for a specific pulse?

I've spent a fair bit of time going over the class reference for this project and the API itself so I'm pretty sure the answer is 'not yet'. I just wanted to do a sanity check in case I'm missing something obvious.

**Comment by allejo** [comment]
Do you mean these?

- http://docs.allejo.io/PhpPulse/master/allejo/DaPulse/Pulse.html#method_getStatusColumn
- http://docs.allejo.io/PhpPulse/master/allejo/DaPulse/Pulse.html#method_getDateColumn
- http://docs.allejo.io/PhpPulse/master/allejo/DaPulse/Pulse.html#method_getNumericColumn
- http://docs.allejo.io/PhpPulse/master/allejo/DaPulse/Pulse.html#method_getPersonColumn
- http://docs.allejo.io/PhpPulse/master/allejo/DaPulse/Pulse.html#method_getTextColumn
- http://docs.allejo.io/PhpPulse/master/allejo/DaPulse/Pulse.html#method_getTimelineColumn

For example, the following usage:

```php
// setting 'true' lazily loads the object so it doesn't make an API call immediately; available since 0.3.0
$pulse = new Pulse(<pulse ID>, true);

$pulse->getTextColumn(<column ID>)->updateValue('my updated text value');
```

**Comment by mattpfeffer** [comment]
So yes, I am being daft. Somehow I missed that method in PulseColumnStatusValue. Much appreciated. Great work on this wrapper btw.

**Comment by allejo** [comment]
Glad I could be of help and thank you! 😄
