### ISSUE TITLE
Add support for "Tags" column type

### ISSUE THREAD

**Issue by allejo** [allejo/PhpPulse#15]
Target branches:

- 0.3.x 
- 0.4.x

**Comment by allejo** [comment]
Does anyone watching/reading this issue have tags in their monday.com plan? My team doesn't so I have no clue what the response for this response of the API endpoint looks like.

**Comment by helpwise** [comment]
Hi Allejo,

Yes - I have this.. what do I do to show you the outpur?  I am a Joomla/PHP dev.

**Comment by allejo** [comment]
Hey @helpwise!

Thanks for offering to help! I don't know *everything* I'm going to need but off the top of my head, I'd need JSON responses from the following endpoints:

- [`GET /v1/boards/{board_id}/columns.json`](https://developers.monday.com/#!/boards/GET_version_boards_board_id_columns_format)
  - I need to see how the JSON response looks like for a board with a Tags column

- [`GET /v1/boards/{board_id}/columns/{column_id}/value.json`](https://developers.monday.com/#!/boards/GET_version_boards_board_id_columns_column_id_value_format)
  - need to see how the response looks like when a Tag column has **no** tags
  - ... when a column **has** tags

- [`PUT /v1/boards/{board_id}/columns/{column_id}/tags.json`](https://developers.monday.com/#!/boards/PUT_version_boards_board_id_columns_column_id_tags_format)
  - the response you get after the PUT request is sent

- [`GET /v1/tags/{id}.json`](https://developers.monday.com/#!/tags/GET_version_tags_id_format)
  - this is in the documentation, however my trust in the monday.com API docs is very low

**Comment by helpwise** [comment]
Hi, here are the responses we get:

- **GET /v1/boards/{board_id}/columns.json**
```
[
  {
    "id": "name",
    "title": "Name",
    "type": "name"
  },
  {
    "id": "last_post",
    "title": "Last Update",
    "type": "lastpost",
    "empty_text": "no updates"
  },
  {
    "type": "tag",
    "title": "Tags",
    "id": "tags"
  }
]
```

- **GET /v1/boards/{board_id}/columns/{column_id}/value.json**

_With tags:_
```
[
  {
    "column_id": "tags",
    "pulse_id": 166******,
    "value": {
      "tag_ids": [
        108****
      ]
    }
  }
]
```

_Without tags:_
```
[
  {
    "column_id": "tags",
    "pulse_id": 166******,
    "value": {
      "tag_ids": []
    }
  }
]
```

- **PUT /v1/boards/{board_id}/columns/{column_id}/tags.json**
```
{
  "column_id": "tags",
  "pulse_id": 166******,
  "value": {
    "tag_ids": [
      108****,
      108****
    ],
    "added_tag": [
      {
        "id": 108****,
        "name": "tagFoo1",
        "color": "black",
        "tag_links_count": 0,
        "board_id": 166******,
        "board_name": "***",
        "board_kind": "private"
      },
      {
        "id": 108****,
        "name": "barTag2",
        "color": "black",
        "tag_links_count": 0,
        "board_id": 166******,
        "board_name": "***",
        "board_kind": "private"
      }
    ]
  }
}
```

- **GET /v1/tags/{id}.json**
```
{
  "url": "https://***.monday.com/tags/108****",
  "id": 108****,
  "name": "barTag2",
  "color": "black",
  "created_at": "2019-01-22T23:21:54Z",
  "updated_at": "2019-01-22T23:21:54Z"
}
```

Hope this helps!

**Comment by allejo** [comment]
Awesome! Thank you! I'll try to get around to implementing this stuff in the coming days
