### ISSUE TITLE
Pagination on fetching Pulses

### ISSUE THREAD

**Issue by allejo** [allejo/PhpPulse#16]
Email update from monday.com sent on Jan 29, 2018.

> We're making changes in our API—important read!
> 
> On the 4th of March, we will add pagination parameters to one endpoint—this parameter will be enabled by default.
> 
> Endpoint: GET /v1/boards/{board_id}/pulses.json
> Returns the board's pulses.These are the two parameters:
>      "per_page": Number of results to return per page. (max value parameter is 25).
>      "page":  Page offset to fetch.
> 
> Please add the "page" and "per_page" parameters to any api call to the `/v1/boards/{board_id}/pulses.json` endpoint.
> 
> This change will affect the number of results you get from this request. The new default value is 15 results (instead of 1000).

**What to do**

Modify `PulseBoard::getPulses()` to have the new `page` and `per_page` parameters. These'll be added with defaults set to null so the monday.com API will be able to determine the necessary behavior.

**Comment by jonpxpx** [comment]
Hey @allejo, do you have an estimated timeframe for this or are you looking for someone to send a pull request through?

**Comment by allejo** [comment]
hey @jonpxpx, PRs are always welcome :) ETA from me would be this week
